#!/bin/bash

OUTPUT="HOSTNAME = $HOSTNAME
TIMEZONE = $TIMEZONE
USER = $USER
OS = $OS
DATE = $DATE
UPTIME = $UPTIME
UPTIME_SEC = $UPTIME_SEC
IP = $IP
MASK = $MASK
GATEWAY = $GATEWAY
RAM_TOTAL = ${RAM_TOTAL} GB
RAM_USED = ${RAM_USED} GB
RAM_FREE = ${RAM_FREE} GB
SPACE_ROOT = ${SPACE_ROOT} MB
SPACE_ROOT_USED = ${SPACE_ROOT_USED} MB
SPACE_ROOT_FREE = ${SPACE_ROOT_FREE} MB"

echo "$OUTPUT"

export OUTPUT_DATA="$OUTPUT"
bash ./to_file.sh